extend = "./pyproject.toml"

line-length = 99
indent-width = 4

# Respect the gitignore by not messing with that stuff
# This is already true by default
respect-gitignore = true

[format]
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Screw yall we preserve quotes here
quote-style = "preserve"

[lint]
# Linting rules we are using
select = [
  "E4",
  "E7",
  "E9",
  "F",  # flake8
  "I",  # isort
  "B",  # flake8-bugbear
  "C4", # flake8-comprehensions
  "NPY",   # numpy
  #"PD",    # pandas
  #"FAST",  # fastapi
  "W191", # tab indentation
  "W291", # trailing whitespace (--fix this)
  "W605", # invalid escape sequence
]

# Linting rules we are ignoring
ignore = [
  "F401",  # unused imports; can just deal w/ that manually
  "E712",  # if a is True. sometimes syntax looks better this way
  "E722",  # allow the bare except if you aint using it
  "E731",  # lambda assignment. screw yall i can do whatever i want
  "C417",  # unnecessary-map; it seems ok syntactically and more readable
]

# Only these rules are fixable when doing `ruff check --fix`
fixable = [
  "E401",
  "E703",
  "E711",
  "I",
  "W191",
]
